name: captain
channels:
  - defaults
  - conda-forge
dependencies:
  - pip=22.1
  - numpy=1.21
  - numba=0.55
  - pandas=1.3
  - matplotlib=3.5
  - seaborn=0.11
  - pip:
    - aiohttp=3.8
    - baltic=0.1
    - build=0.7
    - dendropy=4.5
    - gym=0.21
    - pyinstaller=5.0
    - python-socketio=5.6
    - scipy=1.7
